#!/bin/bash

pid=`ps -ef|grep 'InstallerUI/run'|grep -v grep |awk '{print $2}'`

if [[ $pid ]]; then
    kill $pid
    echo '***INFO: installer web service stopped.'
else
    echo '***INFO: installer web serivce is not running.'
fi
